name: Event Demo1
on:
  pull_request:
    types: [opened]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: First
        run: echo "First Step executed"
      - name: Second
        run:  echo "Second Step executed succesfully"