name: Manual-Job
'on':
  workflow_dispatch:
      
jobs:
  APi-Tests:
    name: Exploring GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: |
          echo  ${GITHUB_API_URL}
          echo "Hello ${qarp_attributes} "
        shell: bash
