name: Manual-Job
'on': push
      
jobs:
  APi-Tests:
    name: Exploring GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: |
          echo  $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/
          echo "Hello ${qarp_attributes} "
        shell: bash
