name: First Workflow
on: 
  workflow_dispatch:
    inputs:
      config_files:
        type: choice
        description: 'select config files'
        required: true
        options: [devCheetah, devStandalone, stageCheetah, stageStandalone]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Printe GoodBye
        run: echo "Done....Bye"
